#홈페이지에서 API서비스 신청시 받은 Appkey, Appsecret 값 설정
APP_KEY: "PSz1w5ad7nLupIhH1R1s0K3PSFkmfzTfiaRV"
APP_SECRET: "fiHq56Hb9NWifu9GPVhNgOzZbgOY97X5aBjbS579uHPXfNHJR+JzjEWts1JwIKa9rE8RylNyVGMt6ejHXaFeF10gIpKGBcIVv0CRJ0Ry1M8Myru3l9dmqsTRLI/ehJ7F34GWBc4bCYe7/gr0kOhEG/QKoXpbt3nIiXGM5n1BHDatvq+UugU="

#계좌번호 앞 8자리
CANO: "50069528"
#계좌번호 뒤 2자리
ACNT_PRDT_CD: "01"

#실전투자
#URL_BASE: "https://openapi.koreainvestment.com:9443"
#모의투자
URL_BASE: "https://openapivts.koreainvestment.com:29443"

#디스코드 웹훅 URL
DISCORD_WEBHOOK_URL: "https://discord.com/api/webhooks/1004031912005877770/NZDaXbl0tIQIMnxydYjXBtzLyPVCTB5Qmogo4KglxbTHOmlT4OC0w1ksvyhMLPZ0_15c"